# Generated by Django 5.2.3 on 2025-06-16 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('artist', models.CharField(default='REIN', max_length=100, verbose_name='Исполнитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='Аудиофайл')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/covers/', verbose_name='Обложка')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Музыкальный трек',
                'verbose_name_plural': 'Музыкальные треки',
                'ordering': ['-created_at'],
            },
        ),
    ]
